## load in Numpy 

In [1]:
import numpy as np

The Basics

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
# Get Size 
a.itemsize

4

In [4]:
# Get shape 
b.shape

NameError: name 'b' is not defined

In [ ]:
# Get Type 
a.dtype

dtype('int32')

In [ ]:
# Get Dimension
a.ndim

1

In [ ]:
# Get total size
a.nbytes

12

In [ ]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements , rows, columns,etc 

In [ ]:
a =np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element [row, column]
a[1,5]

13

In [ ]:
# Get a specific row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
c = np.array([2,4,5,6])
print(c)

[2 4 5 6]


In [ ]:
# Get a specific column
a[: , 2]

array([ 3, 10])

In [ ]:
# Getting a little more fancy  [startindex:endindex:stepsize]
a[0, 0:5:3]

array([1, 4])

In [ ]:
a[1,3] = 20
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 20 12 13 14]]


In [ ]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 13 14]]


## 3-d array

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[8,9]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [8 9]]]


In [ ]:
# Get specific eleemnt 
b[0 ,1 , 1]

4

In [ ]:
# replace 
b[:,1,:] = [[9,9],[9,8]]

In [ ]:
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [9 8]]]


## Initializing Different Types of Arrays

In [ ]:
# All 0s matrix
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# all 1s matrix 
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
# Any other number 
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [ ]:
# Any other number (full_like)
np.full_like(a.shape,4)

array([4, 4])

In [ ]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
# Random decimal number 
np.random.rand(4,2)

array([[0.7054535 , 0.10990715],
       [0.10707821, 0.88088967],
       [0.83929049, 0.31973596],
       [0.22856986, 0.31737867]])

In [ ]:
np.random.random_sample(a.shape)

array([[0.82853383, 0.92584366, 0.82963757, 0.19923453, 0.57939745,
        0.7296441 , 0.7927584 ],
       [0.66717484, 0.76498506, 0.08012955, 0.71171686, 0.70911842,
        0.92049844, 0.33634419]])

In [ ]:
# Random Integer values
np.random.randint (7, size=(3,3))

array([[5, 4, 6],
       [6, 5, 1],
       [4, 1, 0]])

In [ ]:
# the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Repeating an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Be careful when coping arrays!!

In [11]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)

[100   2   3]


### Mathematics

In [12]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [13]:
a-2

array([-1,  0,  1,  2])

In [14]:
a+2

array([3, 4, 5, 6])

In [15]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [16]:
a*2

array([2, 4, 6, 8])

In [17]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [18]:
b = np.array([1,2,3,4])

In [19]:
a+b

array([2, 4, 6, 8])

In [20]:
# Take the sin 
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [22]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra

In [28]:
a = np.ones((2,3))
print(a)

b = np.full((2,3),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2 2]
 [2 2 2]]
