## load in Numpy 

In [ ]:
import numpy as np

: 

The Basics

In [6]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [10]:
# Get Size 
a.itemsize

4

In [12]:
# Get shape 
b.shape

(2, 3)

In [13]:
# Get Type 
a.dtype

dtype('int32')

In [11]:
# Get Dimension
a.ndim

1

In [14]:
# Get total size
a.nbytes

12

In [15]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements , rows, columns,etc 

In [16]:
a =np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
# Get a specific element [row, column]
a[1,5]

13

In [18]:
# Get a specific row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
c = np.array([2,4])
print(c)

: 